# Service composition file for Docker Compose or Podman Compose
# https://cratedb.com/docs/guide/integrate/postgresql/

services:

  cratedb:
    image: docker.io/crate/crate:latest
    command: >
      crate -Cdiscovery.type=single-node
    ports:
      - "4200:4200/tcp"
      - "5432:5432/tcp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/"]
      interval: 5s
      timeout: 30s
      retries: 5

  postgresql:
    image: docker.io/postgres:latest
    command: >
      postgres -c log_statement=all
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "6432:5432/tcp"

  ctk-ingest:
    image: ghcr.io/crate/cratedb-toolkit-ingest:latest
    profiles: ["cli"]
