version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.14"
  jobs:
    # Install `uv`.
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv pip install -r docs/requirements.txt

    # Invoke the build using `uv`.
    build:
      html:
        - ${READTHEDOCS_VIRTUALENV_PATH}/bin/sphinx-build -W -T -b html docs $READTHEDOCS_OUTPUT/html
