# Service composition file for Docker Compose or Podman Compose
# https://cratedb.com/docs/guide/integrate/mongodb/

services:

  cratedb:
    image: docker.io/crate/crate:latest
    command: >
      crate -Cdiscovery.type=single-node
    ports:
      - "4200:4200/tcp"
      - "5432:5432/tcp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/"]
      interval: 5s
      timeout: 30s
      retries: 5

  mongodb:
    image: docker.io/mongo:latest
    ports:
      - "27017:27017/tcp"

  cratedb-toolkit:
    image: ghcr.io/crate/cratedb-toolkit:latest
    profiles: ["cli"]
