# Service composition file for Docker Compose or Podman Compose
# https://cratedb.com/docs/guide/integrate/prometheus/

services:

  cratedb:
    image: "docker.io/crate:latest"
    command: >
      crate -Cdiscovery.type=single-node
    ports:
      - "4200:4200"
      - "5432:5432"
    volumes:
      - cratedb-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/"]
      interval: 5s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  cratedb-ddl:
    image: docker.io/crate/crate:latest
    command: sh -c "crash --hosts http://cratedb:4200/ -c 'SELECT 1'; crash --hosts http://cratedb:4200/ < /var/ddl.sql"
    volumes:
      - ./ddl.sql:/var/ddl.sql
    depends_on:
      - cratedb

  prometheus:
    image: "docker.io/prom/prometheus:latest"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  cratedb-prometheus-adapter:
    image: ghcr.io/crate/cratedb-prometheus-adapter:0.5.8
    command: -config.file /etc/cratedb-prometheus-adapter.yaml
    ports:
      - "9268:9268/tcp"
    volumes:
      - ./cratedb-prometheus-adapter.yaml:/etc/cratedb-prometheus-adapter.yaml
    depends_on:
      - cratedb-ddl
      - prometheus
    restart: unless-stopped

volumes:
  cratedb-data:
