# Service composition file for Docker Compose or Podman Compose

services:

  cratedb:
    image: docker.io/crate/crate:latest
    ports:
      - "4200:4200/tcp"
      - "5432:5432/tcp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/"]
      interval: 5s
      timeout: 30s
      retries: 5

  rabbitmq:
    image: docker.io/rabbitmq:3
    ports:
      - "5672:5672/tcp"

  lorrystream:
    image: ghcr.io/daq-tools/lorrystream:latest
    scale: 0

  amqpcat:
    image: docker.io/cloudamqp/amqpcat:latest
