# Service composition file for Docker Compose or Podman Compose
# https://cratedb.com/docs/guide/integrate/amqp/

services:

  cratedb:
    image: docker.io/crate/crate:latest
    command: >
      crate -Cdiscovery.type=single-node
    ports:
      - "4200:4200/tcp"
      - "5432:5432/tcp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/"]
      interval: 5s
      timeout: 30s
      retries: 5

  rabbitmq:
    image: docker.io/rabbitmq:3
    ports:
      - "5672:5672/tcp"

  lorrystream:
    image: ghcr.io/daq-tools/lorrystream:latest
    profiles: ["cli"]

  amqpcat:
    image: docker.io/cloudamqp/amqpcat:latest
    profiles: ["cli"]
